### ISSUE TITLE
Create sign up function

### ISSUE THREAD

**Issue by kacperzolkiewski** [kacperzolkiewski/CodersCamp2020.CinemaApp#2]
Add sign up functionality to our app where user have to give:
- email
- phone number
- password
- date of birth
- name
- surname

**Comment by mateuszCabala95** [comment]
Don't forget about general properties e.g. min length, max length 

- Password should contain at least 1 uppercase letter and 1 number 
- range of date of birth (e.g. min date of birth id 1900-01-01)
- email validation
