### ISSUE TITLE
[backend] Add necessary information to database

### ISSUE THREAD

**Issue by kgutka** [kacperzolkiewski/CodersCamp2020.CinemaApp#66]
Example of how the MovieCard is rendered:

 `<MovieCard
        imageSource="https://a.allegroimg.com/original/11319f/c05eb92d4ff8b3764c2642d73183/Star-Wars-Skywalker-Odrodzenie-plakat-61x91-5-cm"
        movieTitle="Gwiezdne wojny"
        isPremiere={true}
        movieTrailer="https://www.youtube.com/watch?v=8Qn_spdM5Zg"
      />`

Things to add to our DB: 
- [ ] image of the movie (poster)
- [ ] information if movie is in this moment a premiere
- [ ] link to the trailer

**Comment by mateuszCabala95** [comment]
[] add description to film model
